### ISSUE TITLE
[Bug Report] Crash when trying to download

### ISSUE THREAD

**Issue by p4l3tt3** [Universal-Team/Universal-Updater#76] opened 2021-03-21 21:36 UTC
**Describe the bug**
It crashes when I try to download [Vapecord-ACNL-Plugin](https://github.com/RedShyGuy/Vapecord-ACNL-Plugin)

**To Reproduce**
Try downloading the mentioned plugin, I guess?

**Expected behavior**
It downloads?

**Screenshots**
![image](https://user-images.githubusercontent.com/46242177/111921632-def09100-8a95-11eb-95e4-b05fdafffcf5.png)

**Console/Version (please complete the following information):**

  Console :

  - [ ] 3DS
  - [ ] 3DS XL
  - [ ] 2DS
  - [ ] New 3DS
  - [ ] New 3DS XL
  - [X] New 2DS XL

  Luma & System version:

Luma 3DS version: v10.2.1
System version & Region: Sys 11.14.0-46

**Universal-Updater (please complete the following information):**
  - [X] Release 3.2.0

If Release -> version [example: v2.2.0]

  - [ ] Nightly

If Nightly -> Commit hash [example: a10b9da]

  How do you launch it:

  - [X] cia
  - [ ] 3dsx

**Additional context**
I don't have any

**Comment by SuperSaiyajinStackZ** [comment] 2021-03-21 21:39
Can you reproduce the crash multiple times? Also is it only that one, or do the other ones crash as well?

**Comment by p4l3tt3** [comment] 2021-03-21 21:40
It happened every time (tried 4 or 5 times), and no, that's the only one that crashes

**Comment by SuperSaiyajinStackZ** [comment] 2021-03-21 21:43
Hm, weird. I'm not able to reproduce it, cause it works fine on my end on v3.2.0.. Are you sure your WiFi is stable as well?

**Comment by p4l3tt3** [comment] 2021-03-21 21:51
Ok I just tried again and now the download just fails instantly without crash, but I can still download other things as normal

**Comment by p4l3tt3** [comment] 2021-03-21 21:54
I just tried something, it only crashes if it's already marked as downloaded, if you remove that mark, it starts crashing again when trying

**Comment by SuperSaiyajinStackZ** [comment] 2021-03-21 21:54
Are you trying to download the one for ACNL: Welcome Luxury? If so, afaik that entry is broken there right now and needs to be fixed on Universal-DB's side. I haven't looked into the release build structure changes recently from the release builds of it, but i think it changed.

**Comment by p4l3tt3** [comment] 2021-03-21 21:55
Oh ok yeah I'm trying to download that one, didn't know only that one is broken

**Comment by SuperSaiyajinStackZ** [comment] 2021-03-21 22:00
But hmm yea, interesting to know that it crashes at all.. I might take a look into that around next week or so, when i find the time. The Welcome Luxury Entry will probably be fixed within the next hours. 👍🏻

**Comment by Epicpkmn11** [comment] 2021-03-22 05:31
Should be fixed by Universal-Team/db@4112c43c6b9d742dc9e34494cb9effcddaefcdb3, though it is kinda a problem that it crashes instead of just erroring so I'll leave this open for now at least

**Closed** 2021-03-23 09:20 UTC
Labels: bug
