### ISSUE TITLE
[Bug Report] All apps were gone

### ISSUE THREAD

**Issue by heldernovais** [Universal-Team/Universal-Updater#89] opened 2021-05-25 23:17 UTC
**Describe the bug**
I was download various programs, it ran out of memory, I restarted the 3ds and now all my games and files are gone (except for saves, thankfully).

**Console/Version (please complete the following information):**

  Console :

  - [X ] 3DS
  - [ ] 3DS XL
  - [ ] 2DS
  - [ ] New 3DS
  - [ ] New 3DS XL
  - [ ] New 2DS XL

  Luma & System version:

Luma 3DS version: latest, I don't know. The updater is now also gone.

**Universal-Updater (please complete the following information):**
  - [X] Release

If Release -> version [example: v2.2.0]

  - [ ] Nightly

If Nightly -> Commit hash [example: a10b9da]

  How do you launch it:

  - [X] cia
  - [ ] 3dsx

**Additional context**
It corrupted/deleted my games. Wonderful.

**Comment by heldernovais** [comment] 2021-05-25 23:17
I meant "are" not "were".

**Comment by heldernovais** [comment] 2021-05-25 23:18
DS programs are also gone. GBA Extractions, gone. All but a few things.

**Comment by heldernovais** [comment] 2021-05-25 23:19
FBI errors out when displaying the title list.
Everything is fucked now.

**Comment by heldernovais** [comment] 2021-05-25 23:20
When displaying the list of software in the settings, a message shows up saying:
"The SD Card software management information is corrupted. Reset it now?
This will delete all software and save data."

**Comment by heldernovais** [comment] 2021-05-25 23:21
I can't even see straight. Fuck this software.

**Comment by SuperSaiyajinStackZ** [comment] 2021-05-26 00:09
It's more likely that your SD Card was going to die. Those can be a sign of SD Card corruptions, which sadly can happen every time. That's why backups are **Important**. There is **NO** need to insult the software and there is nothing we can do, so closing this issue.

**Comment by heldernovais** [comment] 2021-05-26 00:29
I ran checks on the SD Card and all resulted positively. The problem is with your code.

**Comment by SuperSaiyajinStackZ** [comment] 2021-05-26 00:33
And what do *you* expect should *we* do? There hasn't been *any* reports of it before happening and i'm **VERY** certain it's **not** the fault of the code.

**Comment by heldernovais** [comment] 2021-05-26 01:04
I expect you to fix your code before anyone else is doomed with the same.
Inspect your code, your libctru, whatever. Good luck

**Comment by NightYoshi370** [comment] 2021-05-26 01:24
Hey, Stack, let me handle this instead.
@heldernovais: Do you have a list of the programs you were trying to download? I want to try recreating this on my Old 3DS XL.

**Comment by heldernovais** [comment] 2021-05-26 01:41
I can't remember. There must have been >10  in queue. Some got downloaded and then they all started failing in sequence (likely lack of free space), so I pressed home. The 3ds crashed and upon reboot all my apps and games were gone except for fbi, play store, settings, etc.
I know it is the software's fault because I did a fsck on my sd card AND the card was nearly full before downloading the programs. I amcertain that running out of space caused it to corrupt the card, as files that had nothing to do with what I was downloading were partially overwritten. Also corrupted tables, etc.
The card's health is fine. No bad chunks and after repairing (and losing all my files) it is still working as intended.

**Comment by heldernovais** [comment] 2021-05-26 01:44
It did succeed in installing some gbc emu with a yellow gameboy for an icon. I didn't run it before resetting everything out of fear that it would corrupt the ticket list further.
Do you know where the list/db is kept (filepath)? I want to try fixing it manually, even if it is a binary file.

**Comment by heldernovais** [comment] 2021-05-26 01:45
A few dsi games survived.

**Comment by NightYoshi370** [comment] 2021-05-26 01:49
Do you have a general idea of what you got? Feel free to check https://db.universal-team.net/ if you don't want to download UU again.

I can tell you got GameYob, based on your description. I don't think that's the problem. Was an app titled "RetroArch" perhaps on your list?

> Do you know where the list/db is kept (filepath)? I want to try fixing it manually, even if it is a binary file.

Sorry, I do not

**Comment by heldernovais** [comment] 2021-05-26 01:51
No, but I did have it installed beforehand. (+ a psx core, I think.)

**Comment by heldernovais** [comment] 2021-05-26 01:52
a few small games, a minecraft clone, twilight menu ++ (my original intention was to update it), that gameyob emu

**Comment by heldernovais** [comment] 2021-05-26 01:52
HoriHD was being downloaded, but I aborted it half-way through as it was bigger than I anticipated. I forgot about this detail.

**Comment by NightYoshi370** [comment] 2021-05-26 01:53
Huh, ok.

Let me see if I could just mess around and try to reproduce this. My best bets would be to try downloading the heavy titles (TWiLight Menu++, RetroArch) and see what happens.

When you say ran out of memory, do you mean RAM or free space on the SD card?

PS: Might be best to stick to as few messages as possible because for every new comment you make, an email about it gets sent to 18 people. It might be worth it to edit your previous comment instead.

**Comment by heldernovais** [comment] 2021-05-26 01:54
ftpd, notepad3ds

**Comment by heldernovais** [comment] 2021-05-26 01:55
Whoops, sorry. I didn't know about that. 

I meant SD Card space.
I didn't dl Retroarch through this program.

**Comment by NightYoshi370** [comment] 2021-05-26 01:58
Hah, no worries. Easy to forget when we're used to real-time communication platforms (like Discord. If you find Discord easier to use than Github and would like to continue there, feel free to join our Discord Server found on our website. Just note there is a lockout system but just DM me there [NightScript#5597] and I can verify you.)

Ah, SD card space. That'll be tougher to pull together but I'll see what I could do. Maybe I could finally put that dummy file generator to use.

Right, I know you didn't download RetroArch through here but I thought to include it because it is quite heavy. I just wanted to download a bunch of heavy applications.

**Comment by Epicpkmn11** [comment] 2021-05-26 03:20
Did a bit of testing, I haven't been able to reproduce UU causing any corruption, I did notice that the extraction wasn't checking that it's file writes were working so just added some safety checks there (f365f87), however I already wasn't able to get anything bad to happen extracting archives without enough free space...

It may be because it let you go to the HOME menu while the queue was running, that should really be disabled and I was able to get a crash once by doing that, nothing beyond a crash though.

**Closed** 2021-05-26 10:47 UTC
Labels: bug

**Comment by Epicpkmn11** [comment] 2021-05-26 10:50
We just added some better safety checks for low SD space with #90, so hopefully this should never happen again.

Also, if you haven't deleted anything from the SD card yet you might want to try running [faketik](https://db.universal-team.net/3ds/faketik), depending on what exactly happened it might be able to fix it, just make sure to free up some space first.

**Comment by heldernovais** [comment] 2021-05-26 19:00
Thank you for your comments. Unfortunately, I have reset everything already, but I was able to backup my saves.

Maybe it'd be a good idea to automatically backup the ticket/app db before altering it? You may need to do this at libctru's level. I'm not sure.
